### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by roblourens** [thieman/better-search#1]
This extension looks great! I can't get it to work - I run Quick Find and enter any query and get 0 results. Anything I can do to help debug it?

It also looks like it only ships the windows version of the ripgrep binary. VS Code extensions have to include native dependencies for all platforms, then select the correct version at runtime. vscode-ripgrep only downloads the version for the current platform, because it was written for vscode where we build separately for each platform.

An easy workaround for you might be to run `npm install vscode-ripgrep` at runtime to get the right version for the user's platform.

**Comment by thieman** [comment]
Thanks for the report, I'll check it out as soon as I can. I developed the whole thing on Ubuntu so the Windows comment is a bit surprising, but we'll get to the bottom of it.

**Comment by roblourens** [comment]
Oh, I was only thinking Windows from glancing at the screenshot. It actually works fine on Ubuntu.

**Comment by thieman** [comment]
I'm trying to figure out how to install the package at runtime like you suggested but I'm hitting a few snags:

1) `require` doesn't seem to work in VSCode, so I'm not sure how to import the package after I've installed it
2) I'm not sure where I should set the `cwd` for the npm install command
3) I'm also not sure whether I can rely on `npm` being installed?

Any chance you have an example of a project that's doing this successfully? All the search extensions I've found just threw `vscode-ripgrep` in their dependencies which is where I got the approach from

Hopefully I'm being an idiot and there's something I can do in `package.json` to make this all magically work, but I didn't see anything

**Comment by roblourens** [comment]
> require doesn't seem to work in VSCode, so I'm not sure how to import the package after I've installed it

Not sure what you mean by that, that is how all packages are imported

> I'm also not sure whether I can rely on npm being installed?

No, you might consider downloading the compressed package directly from npm? https://stackoverflow.com/questions/15035786/download-source-from-npm-without-installing-it/27929112

> Any chance you have an example of a project that's doing this successfully?

There are some more complex extensions that essentially do this (Live Share, C#, C++) but they might not be good examples to copy. 

That was just an idea I had off the top of my head, so no guarantee that it's easy. The alternative is downloading the rg binaries for all platforms, including all of them in your extension, and selecting the right one at runtime. That may be easier.

> All the search extensions I've found just threw vscode-ripgrep in their dependencies which is where I got the approach from

I didn't realize there are other extensions doing this already, can you tell me which ones you saw doing that?

**Comment by thieman** [comment]
> Not sure what you mean by that, that is how all packages are imported

Yeah, maybe this is a peculiarity of trying to run commands inline in the debug console at a breakpoint? That's what I was doing when I couldn't get it to work

> I didn't realize there are other extensions doing this already, can you tell me which ones you saw doing that?

Looked to me like these were doing it:

https://github.com/malkomalko/searchy (this project started off as a fork of searchy, I couldn't get it to work)
https://github.com/bokuweb/vscode-ripgrep

**Comment by thieman** [comment]
Not sure if @ mentioning you in the PR pinged you, but I think I got a fix together for this if you're interested in checking it out. Thanks again for the report and the suggestion!

**Comment by thieman** [comment]
Agh it's an escaping problem, the path on Mac has a space in it 😡 

Welp here comes another version

**Comment by julesx** [comment]
doesnt work for me either. i am on windows. it lists my vs code project workspace root as the search target. finds 0 results.

**Comment by thieman** [comment]
@julesx Any error messages showing up in console or anything? I'll need to dig up a Windows machine to repro

**Comment by thieman** [comment]
@julesx Think we might have got it working with Windows on 0.0.4, give it another shot? You still need to reload the window after the update installs

**Comment by thieman** [comment]
@roblourens Are you still having any issues? Otherwise I'll close this out if Windows support checks out

**Comment by thieman** [comment]
Going to go ahead and close this as we've fixed plenty of issues since it was first reported. Please re-open (or file a new issue) if you're still having trouble
