### ISSUE TITLE
Follow link (ctrl+click) doesn't work on Windows

### ISSUE THREAD

**Issue by dgoldm** [thieman/better-search#18]
On Windows 10 with Git Bash.
In search results window, ctrl+click on underlined file name or line number - an error message pops up with Unknown (FileSystemError).
For instance, ctrl+click on <ins>File: package.json</ins>:
`Unable to open 'package.json': Unable to read file (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\d:\Dev\Test\proj\Dev\Test\proj\package.json'). `

It looks like the path is being added twice to the file name. Also an erroneous double slash is added before the path. Instead of:
`\\d:\Dev\Test\proj\Dev\Test\proj\package.json`
It should have been:
`d:\Dev\Test\proj\package.json`

**Comment by thieman** [comment]
Confirming this bug and that it seems confined to Windows. Taking a look now.

**Comment by thieman** [comment]
Fixed by https://github.com/thieman/better-search/commit/480031c080c0a328c923ee8e7ed1bbb0899553f8
