### ISSUE TITLE
Search fails on Windows

### ISSUE THREAD

**Issue by magnuswahlstrand** [thieman/better-search#7]
Hi there!

I've tried running your extension on a Windows 10 machine with Windows Subsystem for Linux. I don't think the Linux subsystem part matter, except that it gives me very long paths.

I fail to do any of the searches, and after some troubleshooting, I find the following error in the developer tools:

```javascript
Error: Command failed: 'c:\Users\myuser\AppData\Roaming\Code\User\globalStorage\travisthieman.better-search\vscode-ripgrep\package\bin\rg.exe' hej --color never --no-heading --column --line-number --context 5
The filename, directory name, or volume label syntax is incorrect.

	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:182:13)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```
I have gone with Powershell to the cwd.location and executed `$RG_PATH\rg.exe hej` and that works well. Any thoughts on what could be wrong?

/Magnus

**Comment by thieman** [comment]
Probably related to the Windows report in #1. I'm hoping to bust out a Windows machine and figure this out this weekend.

**Comment by magnuswahlstrand** [comment]
Ok! Thanks for letting me know. Let me know if you need any further traces :-)

Feel free to close this as a duplicate.

**Comment by magnuswahlstrand** [comment]
Also: have fun with your windows machine 👍

**Comment by thieman** [comment]
I don't know much about Windows but this looks like my shell escaping tool isn't playing nicely with Windows. The single quotes in your example are no bueno, but it's working without quotes at all (since there are no spaces, I'm guessing) or with double quotes. Fun, fun, portable shell escaping semantics.

**Comment by thieman** [comment]
Yuuuup https://github.com/xxorax/node-shell-escape/issues/9

**Comment by thieman** [comment]
Should be fixed in 0.0.4, let me know if you're still having trouble. You need to reload the VSCode window after installing the update

**Comment by thieman** [comment]
Going to close this issue for now since I don't want passerbys to think it's broken for Windows. Please re-open if you're still having problems

**Comment by magnuswahlstrand** [comment]
Hi! I missed your comment. It works great! Thanks a lot :-)
