### ISSUE TITLE
Default `C-x g` binding interferes with `C-x` for cut?

### ISSUE THREAD

**Issue by thieman** [thieman/better-search#9]
From a dickish 1-star review in the marketplace. Not sure how VSCode handles chords but it'd make sense that this prevents a subset chord from working.

Not sure what makes sense as a "default" keybinding since everyone's going to have different preferences. I use Emacs keybindings which is why I didn't even think about `C-x` being something people use for cut.

**Comment by machineghost** [comment]
Came here file this issue (but for reference I'm not the person who gave that review).  I was excited to try out a better "find", but uninstalled it almost immediately.  To me (and likely 90+% of VS Code users) the extension is fatally flawed.

I'm a Linux user myself (and an emacs user at the command line), but I ascribe to "when in Rome ...". In other words, when I'm using a desktop editor or IDE, I expect it to work like _literally_ every other desktop IDE/editor ... even in Linux.  Every last one has a default keyboard shortcut of CTRL + x to cut (for instance).

I can completely see how you could miss this: your preference for emacs' relatively unique shortcuts, and VS Code's unique "key chord" handling completely explains it.  But hopefully you can understand that it's a MAJOR issue to most users when any extension breaks something as basic (and unrelated) as Copy/Cut/Paste functionality.

**Comment by thieman** [comment]
> to work like literally every other desktop IDE/editor ... even in Linux.

Not saying we shouldn't fix this issue, but I'm an Emacs user where cut is `C-w` and has been since the dawn of computing. 😄 Just in case you're wondering how I could be so insane as to make `C-x g` the default.

Thanks for chiming in, though. Do you have a better suggestion for the default shortcut, or should VSCode extensions even offer default shortcuts?

**Comment by thieman** [comment]
Relatedly, I'm going to go ahead and ship 0.0.5 without the keybinding so people can use it while we figure out what to do.

**Comment by thieman** [comment]
0.0.5 is released and should be rolling out now, @machineghost please give it another try if you're up for it

**Comment by machineghost** [comment]
>Not saying we shouldn't fix this issue, but I'm an Emacs user where cut is C-w and has been since the dawn of computing. smile Just in case you're wondering how I could be so insane as to make C-x g the default.

No insult was intended (again, I use emacs).

I don't categorize Emacs as a "desktop editor"; I think of Sublime, VS Code, or maybe even Notepad as being a desktop editor, but Emacs ... to me Emacs is a command line editor.  It just so happens that you can put said command line editor into a desktop window if you feel like it.

But potato potatoe  :)
